version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql-15.0.2000.1574
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword
