micronaut:
  server:
    port: 1561

akhq:
  connections:
    4-3-0:
      properties:
        bootstrap.servers: "localhost:1559"

    4-2-1:
      properties:
        bootstrap.servers: "localhost:1562"